import React from 'react'
import type { Metadata } from 'next';
import { ChakraProvider, ColorModeProvider } from '@chakra-ui/react';

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function MyApp({ Component, pageProps }): React.JSX.Element {
  return (
    <React.StrictMode>
      <ChakraProvider resetCSS>
        <ColorModeProvider
          options={{
            useSystemColorMode: true,
          }}
        >
          <Component {...pageProps} />
        </ColorModeProvider>
      </ChakraProvider>
    </React.StrictMode>
  )
}

